events {
    worker_connections 1024;
}

http {
    # Aponta para o DNS interno do Docker e atualiza a cada 30s
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        location /api/ {
            # O segredo: colocar o destino em uma variável
            set $backend_api http://collector:8080;
            proxy_pass $backend_api;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /grafana/ {
            # Aplicando a mesma regra para o Grafana
            set $backend_grafana http://grafana:3000;
            proxy_pass $backend_grafana;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            # Aplicando a mesma regra para o Streamlit
            set $backend_streamlit http://streamlit:8501;
            proxy_pass $backend_streamlit;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}